!
!=======================================================================
!
MODULE READ_EXT_FILES
!
!  This module provides the subroutines to read the external files
!
      USE ACCURACY_REAL
      USE DIMENSION_CODE
!
CONTAINS
!
!=======================================================================
!
      SUBROUTINE READ_TL(JEL,IUN,INFILE,IUO1,NAT,A)
!
!  This subroutine reads the T-matrix elements generated by phagen_scf.f
!
!
!
!  Input variables :
!
!                       JEL       :  electron number --> 1 : IN  incoming
!                                                        2 : EX  excited
!                                                        3 : O1  1st outgoing
!                                                        4 : 02  2nd outgoing
!                                                        5 : 03  3rd outgoing
!                       IUN       :  Fortran unit containing the T-matrix elements
!                       INFILE    :  name of file T-matrix file
!                       IUO1      :  Fortran unit for the check file *.lis
!                       NAT       :  number of prototypical atoms
!                       A         :  lattice parameter
!
!  Output variables :   stored in modules
!                       /TL_XX/ with XX = IN, EX,O1,O2,O3 --> spherical wave representation
!                       /TB_XX/ with XX = IN, EX,O1,O2,O3 --> impact parameter representation
!
!
!  The T-matrix elements are stored in the common block corresponding to the
!                  electron(s) involved (_IN,_EX,_O1,_O2,_O3)
!
!  In addition, for the impact parameter case, the radial meshes are stored
!                  in the module R_MESH . The mesh length, whose index
!                  is given by NBMAX_XX(JAT,JE) is the impact parameter equivalent
!                  of LMAX, except that it starts at 1
!
!
!
!
!   Author :  D. Sébilleau
!
!                                     Last modified : 27 May 2021
!
!
      USE APPROXIMATIONS_IN
      USE APPROXIMATIONS_EX
      USE APPROXIMATIONS_O1
      USE APPROXIMATIONS_O2
      USE APPROXIMATIONS_O3
!
      USE ENERGY_IN
      USE ENERGY_EX
      USE ENERGY_O1
      USE ENERGY_O2
      USE ENERGY_O3
!
      USE TLM_IN
      USE TLM_EX
      USE TLM_O1
      USE TLM_O2
      USE TLM_O3
!
      USE TBP_IN
      USE TBP_EX
      USE TBP_O1
      USE TBP_O2
      USE TBP_O3
!
      USE R_MESH
      USE TL_TRUNC
!
      IMPLICIT NONE
!
      CHARACTER (LEN = 30)  ::  DUMMY
      CHARACTER (LEN = 24)  ::  INFILE
!
      INTEGER , INTENT(IN)  ::  JEL,IUN,IUO1,NAT
!
      INTEGER               ::  NE,B
      INTEGER               ::  ITRTL,IPOTC,I_BASIS
      INTEGER               ::  NAT1,NE1,ITL,LMAX_MODE
      INTEGER               ::  ITB,IPOTB
      INTEGER               ::  JE,NLG,NN,NRL,JD
      INTEGER               ::  JAT,NL1,L,NB1
      INTEGER               ::  LMAX(NATM,NE_M),NBMAX(NATM,NE_M)
!
      INTEGER               ::  INT
!
      REAL (WP), INTENT(IN) ::  A
!
      REAL (WP)             ::  EK,SMALL
      REAL (WP)             ::  K2L(NE_M),K2B(NE_M)
!
      COMPLEX (WP)          ::  TLSTAR,TBSTAR
      COMPLEX (WP)          ::  KL(NE_M),KB(NE_M)
      COMPLEX (WP)          ::  TL(0:NT_M,4,NATM,NE_M)
      COMPLEX (WP)          ::  TB(N_MESH_M,4,NATM,NE_M)
!
      COMPLEX (WP)          ::  CONJG
!
      DATA SMALL / 0.0001E0_WP /                                    !
!
!  Opening the T-matrix file
!
      OPEN(UNIT=IUN, FILE=INFILE, STATUS='OLD')                     !
!
!  Choice of electron
!
      IF(JEL == 1) THEN                                             !
        WRITE(IUO1,410)                                             !
        ITRTL   = ITRTL_IN                                          !
        IPOTC   = IPOTC_IN                                          !
        ITL     = ITL_IN                                            !
        I_BASIS = I_BASIS_IN                                        !
        NE      = NE_IN                                             !
      ELSE IF(JEL == 2) THEN                                        !
        WRITE(IUO1,420)                                             !
        ITRTL   = ITRTL_EX                                          !
        IPOTC   = IPOTC_EX                                          !
        ITL     = ITL_EX                                            !
        I_BASIS = I_BASIS_EX                                        !
        NE      = NE_EX                                             !
      ELSE IF(JEL == 3) THEN                                        !
        WRITE(IUO1,430)                                             !
        ITRTL   = ITRTL_O1                                          !
        IPOTC   = IPOTC_O1                                          !
        ITL     = ITL_O1                                            !
        I_BASIS = I_BASIS_O1                                        !
        NE      = NE_O1                                             !
      ELSE IF(JEL == 4) THEN                                        !
        WRITE(IUO1,440)                                             !
        ITRTL   = ITRTL_O2                                          !
        IPOTC   = IPOTC_O2                                          !
        ITL     = ITL_O2                                            !
        I_BASIS = I_BASIS_O2                                        !
        NE      = NE_O2                                             !
      ELSE IF(JEL == 5) THEN                                        !
        WRITE(IUO1,450)                                             !
        ITRTL   = ITRTL_O3                                          !
        IPOTC   = IPOTC_O3                                          !
        ITL     = ITL_O3                                            !
        I_BASIS = I_BASIS_O3                                        !
        NE      = NE_O3                                             !
      END IF                                                        !
!
!  Reading the content of the T-matrix file
!
      IF(I_BASIS <= 1) THEN                                         !
!
!  Partial waves representation
!
        WRITE(IUO1,510)                                             !
        READ(IUN,10) NAT1,NE1,ITL,IPOTC,LMAX_MODE                   !
!
        IF(NAT1 == 1) THEN                                          !
          WRITE(IUO1,110)                                           !
        ELSE                                                        !
          WRITE(IUO1,111) NAT1                                      !
        END IF                                                      !
!
      ELSE IF(I_BASIS == 2) THEN                                    !
!
!  Impact parameter representation
!
        WRITE(IUO1,520)                                             !
        READ(IUN,10) NAT1,NE1,ITB,IPOTB,LMAX_MODE                   !
!
        IF(NAT1 == 1) THEN                                          !
          WRITE(IUO1,112)                                           !
        ELSE                                                        !
          WRITE(IUO1,113) NAT1                                      !
        END IF                                                      !
!
      END IF                                                        !
!
      IF((NAT1 /= NAT) .OR. (NE1 /= NE)) GO TO 310                  !
!
      DO JE = 1, NE                                                 !
!
        IF(I_BASIS <= 1) THEN                                       !
!
!  Partial waves representation
!
          NLG = INT(NAT - SMALL) / 4 + 1                            !
!
!.....  Reading the energy point and the energy
!
          READ(IUN,20) EK                                           !
          WRITE(IUO1,120) JE,EK                                     !
!
          DO NN = 1, NLG                                            !
            NRL = 4 * NN                                            !
            JD  = 4 * (NN - 1) + 1                                  !
            IF(NN == NLG) NRL = NAT                                 !
            READ(IUN,30) (LMAX(JAT,JE),JAT=JD,NRL)                  !
            WRITE(IUO1,130) (LMAX(JAT,JE),JAT=JD,NRL)               !
          END DO                                                    !
          NL1 = 1                                                   !
!
          DO JAT = 1, NAT                                           !
            NL1 = MAX(NL1,LMAX(JAT,1)+1)                            !
          END DO                                                    !
!
          IF(NL1 > NL_M) GO TO 320                                  !
!
          DO JAT = 1, NAT                                           !
            READ(IUN,*) DUMMY                                       !
            DO L = 0, LMAX(JAT,JE)                                  !
!
              READ(IUN,40) KL(JE),TLSTAR                            !
              TL(L,1,JAT,JE) = CONJG(TLSTAR)                        !
              KL(JE)         = CONJG(KL(JE))                        !
!
            END DO                                                  !
          END DO                                                    !
!
          KL(JE)  = KL(JE) * A                                      ! wave number k in unit of 1/A
          K2L(JE) = ABS( KL(JE) * KL(JE) )                          ! |k|^2
!
        ELSE IF(I_BASIS == 2) THEN                                  !
!
!  Impact parameter representation
!
          READ(IUN,70) KB(JE)                                       !
          KB(JE) = CONJG(KB(JE))                                    !
!
          NLG = INT(NAT - SMALL) / 4 + 1                            !
          IF(NE > 1) WRITE(IUO1,120) JE                             !
!
          DO NN = 1, NLG                                            !
            NRL = 4 * NN                                            !
            JD  = 4 * (NN - 1) + 1                                  !
            IF(NN == NLG) NRL = NAT                                 !
            READ(IUN,50) (NBMAX(JAT,JE),JAT=JD,NRL)                 !
            WRITE(IUO1,150) (NBMAX(JAT,JE),JAT=JD,NRL)              !
          END DO                                                    !
!
          NB1 = 1                                                   !
          DO JAT = 1, NAT                                           !
            NB1 = MAX(NL1,NBMAX(JAT,JE))                            !
          END DO                                                    !
          IF(NB1 > N_MESH_M) GO TO 330                              !
!
          DO JAT = 1, NAT                                           !
            READ(IUN,*) DUMMY                                       !
            DO B = 1, NBMAX(JAT,JE)                                 !
!
              READ(IUN,60) B_MESH(JAT,B,JE),TBSTAR                  !
              TB(B,1,JAT,JE) = CONJG(TBSTAR)                        !
!
            END DO                                                  !
          END DO                                                    !
!
          KB(JE)  = KB(JE) * A                                      ! wave number k in unit of 1/A
          K2B(JE) = ABS( KB(JE) * KB(JE) )                          ! |k|^2
!
        END IF                                                      !
!
      END DO                                                        !
!
!  Closing the T-matrix file
!
        CLOSE(IUN)                                                  !
!
!.......... Suppression of possible zeros in the TL array  ..........
!..........  (in case of the use of matrix inversion and   ..........
!..........             for energy variations)             ..........
!
      IF((LMAX_MODE /= 0).AND.(I_BASIS <= 1)) THEN                  !
         CALL SUP_ZEROS(TL,LMAX,NE,NAT,IUO1,ITRTL)                  !
      END IF
!                                                                   !
!  Storing in the corresponding COMMON block
!
!    (1) T-matrix and potential type indices
!
      IF(I_BASIS <= 1) THEN                                         !
!
!  Partial waves representation
!
        IF(JEL == 1) THEN                                           !
         IPOTC_IN = IPOTC                                           !
         ITL_IN   = ITL                                             !
        ELSE IF(JEL == 2) THEN                                      !
         IPOTC_EX = IPOTC                                           !
         ITL_EX   = ITL                                             !
        ELSE IF(JEL == 3) THEN                                      !
         IPOTC_O1 = IPOTC                                           !
         ITL_O1   = ITL                                             !
        ELSE IF(JEL == 4) THEN                                      !
         IPOTC_O2 = IPOTC                                           !
         ITL_O2   = ITL                                             !
        ELSE IF(JEL == 5) THEN                                      !
         IPOTC_O3 = IPOTC                                           !
         ITL_O3   = ITL                                             !
        END IF                                                      !
!
      ELSE IF(I_BASIS == 2) THEN                                    !
!
!  Impact parameter representation
!
        IF(JEL == 1) THEN                                           !
         IPOTB_IN = IPOTB                                           !
         ITB_IN   = ITB                                             !
        ELSE IF(JEL == 2) THEN                                      !
         IPOTB_EX = IPOTB                                           !
         ITB_EX   = ITB                                             !
        ELSE IF(JEL == 3) THEN                                      !
         IPOTB_O1 = IPOTB                                           !
         ITB_O1   = ITB                                             !
        ELSE IF(JEL == 4) THEN                                      !
         IPOTB_O2 = IPOTB                                           !
         ITB_O2   = ITB                                             !
        ELSE IF(JEL == 5) THEN                                      !
         IPOTB_O3 = IPOTB                                           !
         ITB_O3   = ITB                                             !
        END IF                                                      !
!
      END IF                                                        !
!
!    (2) K and K2
!
      DO JE = 1, NE                                                 !
!
        IF(I_BASIS <= 1) THEN                                       !
!
!  Partial waves representation
!
          IF(JEL == 1) THEN                                         !
            KL_IN(JE)  = KL(JE)                                     !
            K2L_IN(JE) = K2L(JE)                                    !
          ELSE IF(JEL == 2) THEN                                    !
            KL_EX(JE)  = KL(JE)                                     !
            K2L_EX(JE) = K2L(JE)                                    !
          ELSE IF(JEL == 3) THEN                                    !
            KL_O1(JE)  = KL(JE)                                     !
            K2L_O1(JE) = K2L(JE)                                    !
          ELSE IF(JEL == 4) THEN                                    !
            KL_O2(JE)  = KL(JE)                                     !
            K2L_O2(JE) = K2L(JE)                                    !
          ELSE IF(JEL == 5) THEN                                    !
            KL_O3(JE)  = KL(JE)                                     !
            K2L_O3(JE) = K2L(JE)                                    !
          END IF                                                    !
!
          DO JAT = 1, NAT                                           !
!
            IF(JEL == 1) THEN                                       !
              LMAX_IN(JAT,JE) = LMAX(JAT,JE)                        !
              DO L = 0, LMAX(JAT,JE)                                !
                TL_IN(L,1,JAT,JE) = TL(L,1,JAT,JE)                  !
              END DO                                                !
            ELSE IF(JEL == 2) THEN                                  !
              LMAX_EX(JAT,JE) = LMAX(JAT,JE)                        !
              DO L = 0, LMAX(JAT,JE)                                !
                TL_EX(L,1,JAT,JE) = TL(L,1,JAT,JE)                  !
              END DO                                                !
            ELSE IF(JEL == 3) THEN                                  !
              LMAX_O1(JAT,JE) = LMAX(JAT,JE)                        !
              DO L = 0, LMAX(JAT,JE)                                !
                TL_O1(L,1,JAT,JE) = TL(L,1,JAT,JE)                  !
              END DO                                                !
            ELSE IF(JEL == 4) THEN                                  !
              LMAX_O2(JAT,JE) = LMAX(JAT,JE)                        !
              DO L = 0, LMAX(JAT,JE)                                !
                TL_O2(L,1,JAT,JE) = TL(L,1,JAT,JE)                  !
              END DO                                                !
            ELSE IF(JEL == 5) THEN                                  !
              LMAX_O3(JAT,JE) = LMAX(JAT,JE)                        !
              DO L = 0, LMAX(JAT,JE)                                !
                TL_O3(L,1,JAT,JE) = TL(L,1,JAT,JE)                  !
              END DO                                                !
            END IF                                                  !
!
          END DO                                                    !
!
        ELSE IF(I_BASIS == 2) THEN                                  !
!
!  Impact parameter representation
!
          IF(JEL == 1) THEN                                         !
            KB_IN(JE)  = KB(JE)                                     !
            K2B_IN(JE) = K2B(JE)                                    !
          ELSE IF(JEL == 2) THEN                                    !
            KB_EX(JE)  = KB(JE)                                     !
            K2B_EX(JE) = K2B(JE)                                    !
          ELSE IF(JEL == 3) THEN                                    !
            KB_O1(JE)  = KB(JE)                                     !
            K2B_O1(JE) = K2B(JE)                                    !
          ELSE IF(JEL == 4) THEN                                    !
            KB_O2(JE)  = KB(JE)                                     !
            K2B_O2(JE) = K2B(JE)                                    !
          ELSE IF(JEL == 5) THEN                                    !
            KB_O3(JE)  = KB(JE)                                     !
            K2B_O3(JE) = K2B(JE)                                    !
          END IF                                                    !
!
          DO JAT = 1, NAT                                           !
!
            IF(JEL == 1) THEN                                       !
              NBMAX_IN(JAT,JE) = NBMAX(JAT,JE)                      !
              DO B = 1, NBMAX(JAT,JE)                               !
                TB_IN(B,1,JAT,JE) = TB(B,1,JAT,JE)                  !
              END DO                                                !
            ELSE IF(JEL == 2) THEN                                  !
              NBMAX_EX(JAT,JE) = NBMAX(JAT,JE)                      !
              DO B = 1, NBMAX(JAT,JE)                               !
                TB_EX(B,1,JAT,JE) = TB(B,1,JAT,JE)                  !
              END DO                                                !
            ELSE IF(JEL == 3) THEN                                  !
              NBMAX_O1(JAT,JE) = NBMAX(JAT,JE)                      !
              DO B = 1, NBMAX(JAT,JE)                               !
                TB_O1(B,1,JAT,JE) = TB(B,1,JAT,JE)                  !
              END DO                                                !
            ELSE IF(JEL == 4) THEN                                  !
              NBMAX_O2(JAT,JE) = NBMAX(JAT,JE)                      !
              DO B = 1, NBMAX(JAT,JE)                               !
                TB_O2(B,1,JAT,JE) = TB(B,1,JAT,JE)                  !
              END DO                                                !
            ELSE IF(JEL == 5) THEN                                  !
              NBMAX_O3(JAT,JE) = NBMAX(JAT,JE)                      !
              DO B = 1, NBMAX(JAT,JE)                               !
                TB_O3(B,1,JAT,JE) = TB(B,1,JAT,JE)                  !
              END DO                                                !
            END IF                                                  !
!
          END DO                                                    !

!
        END IF                                                      !
!
      END DO                                                        !
!
      GO TO 888                                                     !
!
!  Stops: dimension problems
!
 310  WRITE(IUO1,311)                                               !
      STOP                                                          !
 320  WRITE(IUO1,321)                                               !
      STOP                                                          !
 330  WRITE(IUO1,331)                                               !
      STOP                                                          !
!
!  Formats:
!
  10  FORMAT(5(5X,I4))
  20  FORMAT(44X,F8.2)
  30  FORMAT(4(7X,I2))
  40  FORMAT(3X,F9.4,1X,F9.4,5X,E13.6,5X,E13.6)
  50  FORMAT(4(7X,I4))
  60  FORMAT(3E15.7)
  70  FORMAT(32X,f9.4,2X,f9.4)
!
 110  FORMAT(////,18X,'MAXIMAL VALUE OF L FOR THE ',                   &
             'PROTOTYPICAL ATOM : ',//)
 111  FORMAT(////,12X,'MAXIMAL VALUES OF L FOR THE ',I3,               &
             ' PROTOTYPICAL ATOMS : ',//)
 112  FORMAT(////,18X,'MAXIMAL VALUE OF INDEX B FOR THE ',             &
             'PROTOTYPICAL ATOM : ',//)
 113  FORMAT(////,12X,'MAXIMAL VALUES OF INDEX B FOR THE ',I3,         &
             ' PROTOTYPICAL ATOMS : ',//)
 120  FORMAT(//,20X,'ENERGY POINT No ',I3,' :',F8.2,' eV (INTERNAL)',/)
 130  FORMAT(28X,4(I2,5X))
 150  FORMAT(26X,4(I4,3X))
!
 311  FORMAT(///,'<<<<<<<<<<  NAT OR NE DIFFERENT BETWEEN THE INPUT ', &
                'AND T-MATRIX FILES  >>>>>>>>>>')
 321  FORMAT(///,'<<<<<<<<<<  LMAX > NL_M-1 IN THE T-MATRIX ',         &
                'FILE  >>>>>>>>>>')
 331  FORMAT(///,'<<<<<<<<<< NBMAX > N_MESH IN THE T-MATRIX ',         &
                'FILE  >>>>>>>>>>')
!
 410  FORMAT(///,9X,'------------------------  INCOMING ELECTRON  : ', &
             '------------------------')
 420  FORMAT(///,9X,'------------------------  EXCITED  ELECTRON  : ', &
             '------------------------')
 430  FORMAT(///,9X,'------------------------  OUTGOING ELECTRON 1: ', &
             '------------------------')
 440  FORMAT(///,9X,'------------------------  OUTGOING ELECTRON 2: ', &
             '------------------------')
 450  FORMAT(///,9X,'------------------------  OUTGOING ELECTRON 3: ', &
             '------------------------')
!
 510  FORMAT(///,12X,'---> READING T-MATRIX IN SPHERICAL WAVES',       &
                     ' REPRESENTATION')
 520  FORMAT(///,12X,'---> READING T-MATRIX IN IMPACT PARAMETER',      &
                     ' REPRESENTATION')
!
 888  RETURN
!
      END
!
!=======================================================================
!
      SUBROUTINE SUP_ZEROS(TL,LMAX,NE,NAT,IUO1,ITRTL)
!
!   This routine suppresses possible zeros in the TL arrays so that
!     the code runs faster because of lower values of LMAX. Actually,
!     the TL array is not modified, it is just the LMAX array that is
!     altered. This is particularly useful for energy variations or
!     for matrix inversion
!
!
!  Input variables :
!
!                       NE        :  number of energy points
!                       NAT       :  number of prototypical atoms
!                       IUO1      :  Fortran unit for the check file *.lis
!                       ITRTL     :  truncation switch for t_l
!                       TL        :  t-matrix array
!                       LMAX      :  l_max array
!
!  Output variables :
!
!                       LMAX      :  l_max array
!
!
!
!   Author :  D. Sébilleau
!
!                                     Last modified : 19 May 2021
!
!
      IMPLICIT NONE
!
      INTEGER , INTENT(IN)        ::  NE,NAT,IUO1
      INTEGER , INTENT(INOUT)     ::  LMAX(NATM,NE_M),ITRTL
!
      INTEGER                     ::  JE,JAT,NONZERO,LM,L
!
      REAL (WP)                   ::  SMALL
!
      REAL (WP)                   ::  ABS,REAL,AIMAG
!
      COMPLEX (WP)                ::  TL(0:NT_M,4,NATM,NE_M)
!
      COMPLEX (WP)                ::  TL_
!
      IF(ITRTL == 1) THEN                                           !
        SMALL = 0.1E0_WP                                            !
      ELSE IF(ITRTL == 2) THEN                                      !
        SMALL = 0.01E0_WP                                           !
      ELSE IF(ITRTL == 3) THEN                                      !
        SMALL = 0.001E0_WP                                          !
      ELSE IF(ITRTL == 4) THEN                                      !
        SMALL = 0.0001E0_WP                                         !
      ELSE IF(ITRTL == 5) THEN                                      !
        SMALL = 0.00001E0_WP                                        !
      ELSE IF(ITRTL == 6) THEN                                      !
        SMALL = 0.000001E0_WP                                       !
      ELSE IF(ITRTL == 7) THEN                                      !
        SMALL = 0.0000001E0_WP                                      !
      ELSE IF(ITRTL == 8) THEN                                      !
        SMALL = 0.00000001E0_WP                                     !
      ELSE                                                          !
        ITRTL = 9                                                   !
        SMALL = 0.000000001E0_WP                                    !
      END IF                                                        !
!
      WRITE(IUO1,10)                                                !
      WRITE(IUO1,15) ITRTL                                          !
!
      DO JE = 1, NE                                                 !
        WRITE(IUO1,20) JE                                           !
        DO JAT = 1, NAT                                             !
          NONZERO = 0                                               !
          LM = LMAX(JAT,JE)                                         !
          DO L = 0, LM                                              !
            TL_ = TL(L,1,JAT,JE)                                    !
            IF( ( ABS( REAL(TL_)) >= SMALL ) .OR.                 & !
                 (ABS(AIMAG(TL_)) >= SMALL)) THEN                   !
               NONZERO = NONZERO + 1                                !
            END IF                                                  !
          END DO                                                    !
          LMAX(JAT,JE) = NONZERO - 1                                !
          WRITE(IUO1,30) JAT,LM,NONZERO-1                           !
        END DO                                                      !
      END DO                                                        !
!
      WRITE(IUO1,40)                                                !
!
!  Formats:
!
  10  FORMAT(//,'   ---> CHECK FOR ZEROS IN THE TL FILE TO REDUCE', &
                ' THE AMOUNT OF COMPUTING :',/)
  15  FORMAT(/,'  (ONLY THE MATRIX ELEMENTS NON ZERO ',             &
               'TO THE FIRST ',I1,' DECIMAL DIGITS ARE KEPT)',/)
  20  FORMAT(/,15X,'ENERGY POINT No ',I3,/)
  30  FORMAT(8X,'PROTOTYPICAL ATOM No ',I5,'  INITIAL LMAX = ',I2,  &
                  '   FINAL LMAX = ',I2)
  40  FORMAT(//)
!
      END SUBROUTINE SUP_ZEROS
!
!=======================================================================
!
      SUBROUTINE READ_RADIAL(JEL,IUN,INFILE,IUO1)
!
!  This subroutine reads the radial integrals generated by phagen_scf.f
!    in the case of the photon-electron excitation process
!
!
!
!  Input variables :
!
!                       JEL       :  electron number --> 1 : IN  incoming
!                                                        2 : EX  excited
!                                                        3 : O1  1st outgoing
!                                                        4 : 02  2nd outgoing
!                                                        5 : 03  3rd outgoing
!                       IUN       :  Fortran unit containing radial matrix elements
!                       INFILE    :  name of file radial integral file
!                       IUO1      :  Fortran unit for the check file *.lis
!
!  Output variables :
!
!                       RHOR      :  regular photon-electron radial integrals
!                       RHOI      :  irregular photon-electron radial integrals
!                       RHOA      :  Auger radial integrals (Coulomb localized-localized integrals)
!                       RHOL      :  Coulomb delocalized-localized radial integrals
!                       RHOD      :  Coulomb delocalized-delocalized radial integrals,
!
!            where the RHOX are stored in the modules /RADINT_X/
!                 or /RADINT_Xn/ when there are two many arrays
!
!                       RHOI      :  irregular diagonal radial integrals (same storage as RHOR)
!                       RHOI_Xn_Ym:  irregular off-diagonal radial integrals
!
!
!  Conventions for LR (2nd storage index for radial integrals) :
!
!              * LR = 1 : electric dipole channel     LF = LI-1
!              * LR = 2 : electric dipole channel     LF = LI+1
!
!              * LR = 3 : electric quadrupole channel LF = LI-2
!              * LR = 4 : electric quadrupole channel LF = LI
!              * LR = 5 : electric quadrupole channel LF = LI+2
!
!              * LR = 6 : magnetic dipole channel     LF = LI
!
!              * LR = 7 : electric octupole channel   LF = LI-3
!              * LR = 8 : electric octupole channel   LF = LI-1
!              * LR = 9 : electric octupole channel   LF = LI+1
!              * LR = 10: electric octupole channel   LF = LI+3
!
!              * the magnetic quadrupole / polar toroidal dipole
!                integral is the same as that of the electric dipole
!
!
!  Warning: there are two ways to define the irregular wave functions
!           entering the irregular radial integrals entering the
!           expression of the XAS/REXS cross-section:

!             (1) G(r,r') =  R Tau R' + R J                J irregular
!             (2) G(r,r') =  R (Tau - T)R' + R H           H irregular
!
!           phagen_scf.f computes the irregular radial integrals with H
!           so that we need to use expansion (2) in the expression of
!           the cross-sections
!
!
!  Note: the radial wave function in phagen_scf.f are normalized
!         at one state per Rydberg, which means that each final state
!         radial wave function matches smoothly to
!
!                        1/2           _                    _
!                (  k   )        -1   |                (2)   |
!                ( ---- )     t_l     |  j_l(kr) - i h_l(kr) |
!                (  pi  )             |_                    _|
!
!
!
!
!
!   Author :  D. Sébilleau
!
!                                     Last modified : 28 May 2021
!
!
      USE COMPLEX_NUMBERS,      ONLY : ZEROC,ONEC
!
      USE AUGER_PARAM
      USE EXP_TYPE
      USE INIT_A
      USE INIT_J
      USE INIT_L
      USE INIT_M
      USE OPTICAL_ELTS
!
      USE ENERGY_IN
      USE ENERGY_EX
      USE ENERGY_O1
      USE ENERGY_O2
      USE ENERGY_O3
!
      USE TEST_O1
      USE TEST_O2
!
      USE RADINT_L1              !  \
      USE RADINT_L2              !   \
      USE RADINT_L3              !    \   EELS/(e,2e)
      USE RADINT_L4              !    /   radial integrals
      USE RADINT_L5              !   /
      USE RADINT_L6              !  /
!
      USE RADINT_R               !  \
      USE RADINT_I               !   >    PED/XAS/REXS radial integrals
      USE RAD_E1E2               !  /
!
      USE RADINT_A               ! -->    Auger radial integrals
!
      IMPLICIT NONE
!
      CHARACTER (LEN = 24)        ::  INFILE
      CHARACTER (LEN =  9)        ::  RAD_TYPE
      CHARACTER (LEN =  1)        ::  DUMMY
!
      INTEGER , INTENT(IN)        ::  JEL,IUN,IUO1
!
      INTEGER                     ::  NE
      INTEGER                     ::  I_TEST_A
      INTEGER                     ::  NLINE_1(NE_M),NLINE_2(NE_M)
      INTEGER                     ::  NLINE_3(NE_M),NLINE_4(NE_M)
      INTEGER                     ::  NLINE_5(NE_M),NLINE_6(NE_M)
      INTEGER                     ::  JTE,JDUM,JM,JE,JLINE,JL,JAT
      INTEGER                     ::  LE1,LE2
      INTEGER                     ::  IERR,I_RD_FILE
      INTEGER                     ::  L_A,L_C1,L_C2,L_CO_MAX
      INTEGER                     ::  L_E,L_E1,L_E2
      INTEGER                     ::  L_EX,L_IN,L_SC
      INTEGER                     ::  L_IN_MAX,L_EX_MAX,L_SC_MAX
      INTEGER                     ::  LA,LA_MIN,LA_MAX
      INTEGER                     ::  LB,LB_MIN,LB_MAX
      INTEGER                     ::  LE,LE_MIN1,LE_MAX1
      INTEGER                     ::  LI_C2,LI_I2,LI_A2
      INTEGER                     ::  N_CHANNEL
!
      COMPLEX (WP)                ::  RHOR1STAR,RHOR2STAR,RHOR3STAR,RHOR4STAR
      COMPLEX (WP)                ::  RHOR5STAR,RHOR6STAR,RHOR7STAR,RHOR8STAR
      COMPLEX (WP)                ::  RHOR9STAR,RHOR10STAR
      COMPLEX (WP)                ::  RHOI1STAR,RHOI2STAR,RHOI3STAR,RHOI4STAR
      COMPLEX (WP)                ::  RHOI5STAR,RHOI6STAR,RHOI7STAR,RHOI8STAR
      COMPLEX (WP)                ::  RHOI9STAR,RHOI10STAR
      COMPLEX (WP)                ::  RAD,RAD_D,RAD_E
!
      COMPLEX (WP)                ::  CONJG
!
      I_TEST_A = 0                                                  !
      IF(SPECTRO == 'AED') THEN                                     !
        I_TEST_A = I_TEST_O1                                        !
      ELSE IF(SPECTRO == 'APC') THEN                                !
        I_TEST_A = I_TEST_O2                                        !
      END IF
!
      IF(JEL == 1) THEN                                             !
        NE      = NE_IN                                             !
      ELSE IF(JEL == 2) THEN                                        !
        NE      = NE_EX                                             !
      ELSE IF(JEL == 3) THEN                                        !
        NE      = NE_O1                                             !
      ELSE IF(JEL == 4) THEN                                        !
        NE      = NE_O2                                             !
      ELSE IF(JEL == 5) THEN                                        !
        NE      = NE_O3                                             !
      END IF                                                        !
!
      JTE = 1                                                       !
!
!  Opening the radial integral file
!
      OPEN(UNIT=IUN, FILE=INFILE, STATUS='OLD')                     !
!
!  Type of excitation
!
      IF(EXCITATION(JEL) == 'PH-ELEC') THEN                         !
!
!..... Photon-electron interaction
!
!  Skipping the headers
!
        DO JDUM = 1, 7                                              !
           READ(IUN,100) DUMMY                                      !
        END DO                                                      !
!
        JM = 1                                                      ! absorber index. Always 1
!                                                                   !    for phagen_scf.f
        DO JE = 1, NE                                               !
!
!     Reading regular radial integrals
!
          READ(IUN,101) RHOR1STAR,RHOR2STAR,RHOR3STAR,RHOR4STAR,  & ! phagen_scf.f uses the
                        RHOR5STAR,RHOR6STAR,RHOR7STAR,RHOR8STAR,  & ! incoming wave convention,
                        RHOR9STAR,RHOR10STAR,RAD_TYPE               ! so we need to take the
!                                                                   ! complex conjugate
          IF((SPECTRO == 'XAS') .OR. (SPECTRO == 'RES')) THEN       !
!
!     Reading irregular diagonal radial integrals (i.e. E1-E1, E1-E2, ...)
!
            READ(IUN,101) RHOI1STAR,RHOI2STAR,RHOI3STAR,RHOI4STAR,& !
                          RHOI5STAR,RHOI6STAR,RHOI7STAR,RHOI8STAR,& !
                          RHOI9STAR,RHOI10STAR,RAD_TYPE             !
!
!     Reading irregular off-diagonal radial integrals : E1-E2
!
            DO JLINE = 1, 5                                         !
             READ(IUN,100) DUMMY                                    ! skipping the headers
            END DO                                                  !
            DO LE1 = 1 , 2                                          ! number of L-allowed values for E1
              DO LE2 = 1, 3                                         ! number of L-allowed values for E2
                READ(IUN,102) L_E1,L_E2,RAD                         !
                RHOI_E1_E2(JE,LE1,LE2) = CONJG(RAD)                 !
              END DO                                                !
            END DO                                                  !
            READ(IUN,100) DUMMY                                     !
!
          END IF                                                    !
!
          IF(RAD_TYPE == 'regular  ') THEN                          !
!
            RHOR(JE,1,1,JEL)  = CONJG(RHOR1STAR)                    ! LI-1 for E1  =  LI-1 for M2
            RHOR(JE,2,1,JEL)  = CONJG(RHOR2STAR)                    ! LI+1 for E1  =  LI+1 for M2
            RHOR(JE,3,1,JEL)  = CONJG(RHOR3STAR)                    ! LI-2 for E2
            RHOR(JE,4,1,JEL)  = CONJG(RHOR4STAR)                    ! LI   for E2
            RHOR(JE,5,1,JEL)  = CONJG(RHOR5STAR)                    ! LI+2 for E2
            RHOR(JE,6,1,JEL)  = CONJG(RHOR6STAR)                    ! LI   for M1
            RHOR(JE,7,1,JEL)  = CONJG(RHOR7STAR)                    ! LI-3 for E3
            RHOR(JE,8,1,JEL)  = CONJG(RHOR8STAR)                    ! LI-1 for E3
            RHOR(JE,9,1,JEL)  = CONJG(RHOR9STAR)                    ! LI+1 for E3
            RHOR(JE,10,1,JEL) = CONJG(RHOR10STAR)                   ! LI+3 for E3
!
          ELSE IF(RAD_TYPE == 'irregular') THEN
!
!.....  Diagonal integrals  .....
!
            RHOI(JE,1,1,JEL)   =CONJG(RHOI1STAR)                    ! (LI-1,LI-1) for E1-E1
            RHOI(JE,2,1,JEL)  = CONJG(RHOI2STAR)                    ! (LI+1,LI+1) for E1-E1
            RHOI(JE,3,1,JEL)  = CONJG(RHOI3STAR)                    ! (LI-2,LI-2) for E2-E2
            RHOI(JE,4,1,JEL)  = CONJG(RHOI4STAR)                    ! (LI,LI)     for E2-E2
            RHOI(JE,5,1,JEL)  = CONJG(RHOI5STAR)                    ! (LI+2,LI+2) for E2-E2
            RHOI(JE,6,1,JEL)  = CONJG(RHOI6STAR)                    ! (LI,LI)     for M1-M1
            RHOI(JE,7,1,JEL)  = CONJG(RHOI7STAR)                    ! (LI-3,LI-3) for E3-E3
            RHOI(JE,8,1,JEL)  = CONJG(RHOI8STAR)                    ! (LI-1,LI-1) for E3-E3
            RHOI(JE,9,1,JEL)  = CONJG(RHOI9STAR)                    ! (LI+1,LI+1) for E3-E3
            RHOI(JE,10,1,JEL) = CONJG(RHOI10STAR)                   ! (LI+3,LI+3) for E3-E3
!
          END IF                                                    !
!
        END DO                                                      !
!
!..... Auger interaction: Coulomb interaction between two localized electrons/holes
!
      ELSE IF(EXCITATION(JEL) == 'COUL-LL') THEN                    !
!
!  Error flags
!
        IERR      = 0                                               !
        I_RD_FILE = 0                                               !
!
        IF(I_MULT == 0) THEN                                        !
          LE_MIN = ABS(LI_C - ABS(LI_I-LI_A))                       ! L selection rule for
          LE_MAX  =LI_C + LI_A + LI_I                               ! the escaping Auger electron
        ELSE
          LE_MIN = ABS(LI_C - L_MUL)                                !
          LE_MAX = LI_C + L_MUL                                     !
        END IF                                                      !
!
!  Reading the headers
!                                                                   ! LI_C = L of the primary core state
        DO JLINE = 1, 3                                             !
          READ(IUN,100) DUMMY                                       ! skipping the headers
        END DO                                                      !
!
        READ(IUN,200) LI_C2,LI_I2,LI_A2                             ! LI_I = L of the electron that decays
        READ(IUN,201) LE_MIN1,N_CHANNEL                             ! LI_A = L of the electron to be ejected
        LE_MAX1 = LE_MIN1 + N_CHANNEL - 1                           !
        IF(I_TEST_A /= 1) THEN                                      !
          IF( (LE_MIN /= LE_MIN1) .OR.                            & ! consistency of radial integrals file
              (LE_MAX /= LE_MAX1) ) GO TO 300                       ! with input data file
        ELSE                                                        !
          LI_C2     = 0                                             !
          LI_I2     = 1                                             !
          LI_A2     = 0                                             !
          LE_MIN1   = 1                                             !
          N_CHANNEL = 1                                             !
        END IF                                                      !
!
        IF(LI_C /= LI_C2) I_RD_FILE = 1                             ! inconsistencies between
        IF(LI_I /= LI_I2) I_RD_FILE = 1                             ! input data file and
        IF(LI_A /= LI_A2) I_RD_FILE = 1                             ! radial integrals file
!
        IF(LE_MAX > LI_M) GO TO 310                                 !
!
        DO LE = LE_MIN, LE_MAX                                      ! LE  = L of the escaping Auger electron
          READ(IUN,202) L_E,LB_MIN,LB_MAX                           !   No loop on energy here
          IF(I_TEST_A == 1) THEN                                    !
            L_E    = 1                                              !
            LB_MIN = 0                                              !
            LB_MAX = 1                                              !
          END IF                                                    !
          IF(LE /= L_E) IERR = 1                                    !
!
          L_BOUNDS(L_E,1) = LB_MIN                                  ! storage of LB_MIN and LB_MAX
          L_BOUNDS(L_E,2) = LB_MAX                                  ! for each L_E for further use
!
          DO LB = LB_MIN, LB_MAX                                    ! LB  = L of the Coulomb field
            READ(IUN,203) L_A,RAD_D,RAD_E                           ! L_A = L of the escaping Auger electron
            RHOA(LE,L_A,1,1,JEL) = CONJG(RAD_D)                     ! direct integral
            RHOA(LE,L_A,2,1,JEL) = CONJG(RAD_E)                     ! exchange integral
            IF(I_TEST_A == 1) THEN                                  !
              IF(LB == LB_MIN) THEN                                 ! test case : effect of radial
                RHOA(LE,L_A,1,1,JEL) = ZEROC                        !  integrals removed :
                RHOA(LE,L_A,2,1,JEL) = ONEC                         ! only multiple scattering
              ELSE IF(LB == LB_MAX) THEN                            ! taken into account
                RHOA(LE,L_A,1,1,JEL) = ONEC                         !
                RHOA(LE,L_A,2,1,JEL) = ZEROC                        !
              END IF                                                !
            END IF                                                  !
          END DO                                                    !
!
        END DO                                                      ! end of loop on L_E
!
        IF(IERR == 1) GO TO 300                                     !
        IF(I_RD_FILE == 1) GO TO 300                                !
!
!..... Coulomb interaction between one delocalized electron and one localized electron
!.....       EELS and (e,2e) case. Those of modulus lower than 1.E-9 are neglected
!.....
!..... L_IN : l angular momentum of incoming electron
!..... L_SC : l angular momentum of scattered electron
!..... L_EX : l angular momentum of excited electron
!..... L_C1 : l angular momentum of Coulomb field
!..... L_C2 : l angular momentum of Coulomb field
!.....
!..... Absorber index skipped when reading the radial integrals as always 1 in phagen_scf.f
!
      ELSE IF(EXCITATION(JEL) == 'COUL-DL') THEN                    !
!
        CALL INIT_EELS_ARRAYS(RHOL_00_RD,RHOL_00_RE,RHOL_0J_RD,   & ! initialization of radial arrays
                              RHOL_0J_RE,RHOL_ID,RHOL_IE)           !
        CALL FIND_EELS_BLOCKS(IUN,IUO1,NE,NLINE_1,NLINE_2,NLINE_3,& ! find the length of each block
                              NLINE_4,NLINE_5,NLINE_6)              ! of data to be read from radial file
!
!  Initialization of the l_max of each angular momentum (to be able to decrease
!              the storage of the radial integrals if necessary)
!
        L_IN_MAX = 0                                                ! incoming electron
        L_SC_MAX = 0                                                ! scattered electron
        L_EX_MAX = 0                                                ! excited electron
        L_CO_MAX = 0                                                ! Coulomb field
!
!  Skipping the headers
!
        DO JL = 1, 3                                                !
          READ(IUN,100) DUMMY                                       !
        END DO                                                      !
!
        DO JE = 1, NE                                               !
!
          READ(IUN,100) DUMMY                                       ! line with energy point number
!
!  (1) Reading the single site regular direct radial integrals
!
          READ(IUN,100) DUMMY                                       ! line with text
          READ(IUN,100) DUMMY                                       ! line with ------
!
          DO JLINE = 1, NLINE_1(JE)                                 !
            READ(IUN,250) L_EX,L_IN,L_SC,L_C1,RAD                   !
            RHOL_00_RD(JE,L_EX,L_IN,L_SC,L_C1) = CONJG(RAD)         !
            L_IN_MAX = MAX(L_IN,L_IN_MAX)                           !
            L_SC_MAX = MAX(L_SC,L_SC_MAX)                           !
            L_EX_MAX = MAX(L_EX,L_EX_MAX)                           !
            L_CO_MAX = MAX(L_C1,L_CO_MAX)                           !
          END DO                                                    !
!
          READ(IUN,100) DUMMY                                       ! line with ------
!
!  (2) Reading the two-site regular direct radial integrals
!
          READ(IUN,100) DUMMY                                       ! line with text
          READ(IUN,100) DUMMY                                       ! line with ------
!
          DO JLINE = 1, NLINE_2(JE)                                 !
            READ(IUN,260) JAT,L_EX,L_IN,L_SC,L_C1,L_C2,RAD          !
            RHOL_0J_RD(JE,JAT,L_EX,L_IN,L_SC,L_C1,L_C2) = CONJG(RAD)!
            L_IN_MAX = MAX(L_IN,L_IN_MAX)                           !
            L_SC_MAX = MAX(L_SC,L_SC_MAX)                           !
            L_EX_MAX = MAX(L_EX,L_EX_MAX)                           !
            L_CO_MAX = MAX(L_C1,L_C2,L_CO_MAX)                      !
          END DO                                                    !
!
          READ(IUN,100) DUMMY                                       ! line with ------
!
!  (3) Reading the single site regular exchange radial integrals
!
          READ(IUN,100) DUMMY                                       ! line with text
          READ(IUN,100) DUMMY                                       ! line with ------
!
          DO JLINE = 1, NLINE_3(JE)                                 !
            READ(IUN,250) L_EX,L_IN,L_SC,L_C1,RAD                   !
            RHOL_00_RE(JE,L_EX,L_IN,L_SC,L_C1) = CONJG(RAD)         !
            L_IN_MAX = MAX(L_IN,L_IN_MAX)                           !
            L_SC_MAX = MAX(L_SC,L_SC_MAX)                           !
            L_EX_MAX = MAX(L_EX,L_EX_MAX)                           !
            L_CO_MAX = MAX(L_C1,L_CO_MAX)                           !
          END DO
!
          READ(IUN,100) DUMMY                                       ! line with ------
!
!  (4) Reading the two-site regular exchange radial integrals
!
          READ(IUN,100) DUMMY                                       ! line with text
          READ(IUN,100) DUMMY                                       ! line with ------
!
          DO JLINE = 1, NLINE_4(JE)                                 !
            READ(IUN,260) JAT,L_EX,L_IN,L_SC,L_C1,L_C2,RAD          !
            RHOL_0J_RE(JE,JAT,L_EX,L_IN,L_SC,L_C1,L_C2) = CONJG(RAD)!
            L_IN_MAX = MAX(L_IN,L_IN_MAX)                           !
            L_SC_MAX = MAX(L_SC,L_SC_MAX)                           !
            L_EX_MAX = MAX(L_EX,L_EX_MAX)                           !
            L_CO_MAX = MAX(L_C1,L_C2,L_CO_MAX)                      !
          END DO                                                    !
!
          READ(IUN,100) DUMMY                                       ! line with ------
!
!  (5) Reading the irregular direct radial integrals
!
          READ(IUN,100) DUMMY                                       ! line with text
          READ(IUN,100) DUMMY                                       ! line with ------
!
          DO JLINE = 1, NLINE_5(JE)                                 !
            READ(IUN,250) L_EX,L_IN,L_SC,L_C1,RAD                   !
            RHOL_ID(JE,L_EX,L_IN,L_SC,L_C1) = CONJG(RAD)            !
            L_IN_MAX = MAX(L_IN,L_IN_MAX)                           !
            L_SC_MAX = MAX(L_SC,L_SC_MAX)                           !
            L_EX_MAX = MAX(L_EX,L_EX_MAX)                           !
            L_CO_MAX = MAX(L_C1,L_CO_MAX)                           !
          END DO                                                    !
!
          READ(IUN,100) DUMMY                                       ! line with ------
!
!  (6) Reading the irregular exchange radial integrals
!
          READ(IUN,100) DUMMY                                       ! line with text
          READ(IUN,100) DUMMY                                       ! line with ------
!
          DO JLINE = 1, NLINE_6(JE)                                 !
            READ(IUN,250) L_EX,L_IN,L_SC,L_C1,RAD                   !
            RHOL_IE(JE,L_EX,L_IN,L_SC,L_C1) = CONJG(RAD)            !
            L_IN_MAX = MAX(L_IN,L_IN_MAX)                           !
            L_SC_MAX = MAX(L_SC,L_SC_MAX)                           !
            L_EX_MAX = MAX(L_EX,L_EX_MAX)                           !
            L_CO_MAX  =MAX(L_C1,L_CO_MAX)                           !
          END DO                                                    !
!
          READ(IUN,100) DUMMY                                       ! line with ------
!
!  End of energy loop
!
        END DO                                                      !
!
!..... Coulomb interaction between two delocalized electrons
!
      ELSE IF(EXCITATION(JEL) == 'COUL-DD') THEN                    !
!
        CONTINUE                                                    ! Not implemented in phagen_scf.f yet
!
      END IF                                                        !
!
!  Closing the radial integral file
!
      CLOSE(IUN)                                                    !
!
!  Writing the photon-electron radial integral into the check file
!
      IF(EXCITATION(JEL) == 'PH-ELEC') THEN                         !
!
        IF(I_E1 == 1) THEN                                          !
          WRITE(IUO1,400)                                           !
          IF(LI >= 1) THEN                                          !
            WRITE(IUO1,500) LI,LI-1,LI+1                            !
          ELSE                                                      !
            WRITE(IUO1,501) LI,LI+1                                 !
          END IF                                                    !
          IF(I_SO == 1) THEN                                        !
            WRITE(IUO1,502) S_O                                     !
          END IF                                                    !
          DO JE = 1, NE                                             !
            WRITE(IUO1,503) JTE,RHOR(JE,1,1,JEL),LI,LI-1,         & !
                                RHOR(JE,2,1,JEL),LI,LI+1            !
          END DO                                                    !
        END IF                                                      !
!
        IF(I_E2 == 1) THEN                                          !
          WRITE(IUO1,401)                                           !
          IF(LI >= 2) THEN                                          !
            WRITE(IUO1,508) LI,LI-2,LI,LI+2                         !
          ELSE IF(LI == 1) THEN                                     !
            WRITE(IUO1,500) LI,LI,LI+2                              !
          END IF                                                    !
          IF(I_SO == 1) THEN                                        !
            WRITE(IUO1,502) S_O                                     !
          END IF                                                    !
          DO JE = 1, NE                                             !
            WRITE(IUO1,504) JTE,RHOR(JE,3,1,JEL),LI,LI-2,         & !
                                RHOR(JE,4,1,JEL),LI,LI,           & !
                                RHOR(JE,5,1,JEL),LI,LI+2            !
          END DO                                                    !
        END IF                                                      !
!
        IF(I_E3 == 1) THEN                                          !
          WRITE(IUO1,402)                                           !
          IF(LI >= 3) THEN                                          !
            WRITE(IUO1,509) LI,LI-3,LI-1,LI+1,LI+3                  !
          ELSE IF((LI >= 1).AND.(LI < 3)) THEN                      !
            WRITE(IUO1,508) LI,LI-1,LI+1,LI+3                       !
          ELSE IF(LI == 0) THEN                                     !
            WRITE(IUO1,500) LI,LI+1,LI+3                            !
          END IF                                                    !
          IF(I_SO == 1) THEN                                        !
            WRITE(IUO1,502) S_O                                     !
          END IF                                                    !
          DO JE = 1, NE                                             !
            WRITE(IUO1,505) JTE,RHOR(JE,7,1,JEL),LI,LI-3,         & !
                                RHOR(JE,8,1,JEL),LI,LI-1,         & !
                                RHOR(JE,9,1,JEL),LI,LI+1,         & !
                                RHOR(JE,10,1,JEL),LI,LI+3           !
          END DO                                                    !
        END IF                                                      !
!
        IF(I_M1 == 1) THEN                                          !
          WRITE(IUO1,403)                                           !
          WRITE(IUO1,501) LI,LI                                     !
          IF(I_SO == 1) THEN                                        !
            WRITE(IUO1,502) S_O                                     !
          END IF                                                    !
          DO JE = 1, NE                                             !
            WRITE(IUO1,506) JTE,RHOR(JE,6,1,JEL),LI,LI              !
          END DO                                                    !
        END IF                                                      !
!
        IF(I_M2 == 1) THEN                                          !
          WRITE(IUO1,404)                                           !
          IF(LI >= 1) THEN                                          !
            WRITE(IUO1,500) LI,LI-1,LI+1                            !
          ELSE                                                      !
            WRITE(IUO1,501) LI,LI+1                                 !
          END IF                                                    !
          IF(I_SO == 1) THEN                                        !
            WRITE(IUO1,502) S_O                                     !
          END IF                                                    !
          DO JE = 1, NE                                             !
            WRITE(IUO1,503) JTE,RHOR(JE,1,1,JEL),LI,LI-1,         & !
                                RHOR(JE,2,1,JEL),LI,LI+1            !
          END DO                                                    !
        END IF                                                      !
!
        IF(I_C1 == 1) THEN                                          !
          WRITE(IUO1,405)                                           !
          IF(SELRULE == '-1>E1') THEN                               !
            WRITE(IUO1,501) LI,LI-1                                 !
            DO JE = 1, NE                                           !
              WRITE(IUO1,506) JTE,RHOR(JE,1,1,JEL),LI,LI-1          !
            END DO                                                  !
          ELSE IF(SELRULE == '+1>E1') THEN                          !
            WRITE(IUO1,501) LI,LI+1                                 !
            DO JE = 1, NE                                           !
              WRITE(IUO1,506) JTE,RHOR(JE,2,1,JEL),LI,LI+1          !
            END DO                                                  !
          END IF                                                    !
          IF(I_SO == 1) THEN                                        !
            WRITE(IUO1,502) S_O                                     !
          END IF                                                    !
        END IF                                                      !
!
!  Writing Auger radial integrals into the check file
!    (LL : localized electron - localized electron case)
!
      ELSE IF(EXCITATION(JEL) == 'COUL-LL') THEN                    !
!
        JTE = 1                                                     !
        WRITE(IUO1,600) JTE                                         !
        DO LE = LE_MIN, LE_MAX                                      !
          WRITE(IUO1,601) LE                                        !
          LA_MIN = L_BOUNDS(LE,1)                                   !
          LA_MAX = L_BOUNDS(LE,2)                                   !
          DO LA = LA_MIN, LA_MAX                                    !
            WRITE(IUO1,602) LA,RHOA(LE,LA,1,1,JEL),               & !
                               RHOA(LE,LA,2,1,JEL)                  !
          END DO                                                    !
        END DO                                                      !
!
!  Writing Coulomb radial integrals information into the check file
!    (DL : delocalized electron - localized electron case)
!
      ELSE IF(EXCITATION(JEL) == 'COUL-DL') THEN                    !
!
        WRITE(IUO1,603) L_IN_MAX                                    !
        WRITE(IUO1,604) L_SC_MAX                                    !
        WRITE(IUO1,605) L_EX_MAX                                    !
        WRITE(IUO1,606) L_CO_MAX                                    !
!
!  Writing Coulomb radial integrals into the check file
!    (DD : delocalized electron - delocalized electron case)
!
      ELSE IF(EXCITATION(JEL) == 'COUL-DD') THEN                    !
!
        CONTINUE                                                    !
!
!  No interaction case
!
      ELSE IF(EXCITATION(JEL) == 'NOINTER') THEN                    !
!
        WRITE(IUO1,700)                                             !
!
      END IF                                                        !
!
      GO TO 888                                                     !
!
!  Stops: dimension errors
!
 300  WRITE(IUO1,301)                                               !
      STOP                                                          !
 310  WRITE(IUO1,311) LE_MAX                                        !
      STOP                                                          !
!
!  Formats:
!
!  Reading: photon-electron integrals
!
 100  FORMAT(A1)
 101  FORMAT(1X,E12.5,1X,E12.5,2X,E12.5,1X,E12.5,4X,E12.5,1X,E12.5, &
             2X,E12.5,1X,E12.5,2X,E12.5,1X,E12.5,4X,E12.5,1X,E12.5, &
             4X,E12.5,1X,E12.5,2X,E12.5,1X,E12.5,2X,E12.5,1X,E12.5, &
             2X,E12.5,1X,E12.5,5X,A9)
 102  FORMAT(33X,I3,8X,I3,7X,E12.5,1X,E12.5)
!
! Reading: Auger integrals
!
 200  FORMAT(5X,I2,5X,I2,5X,I2)
 201  FORMAT(12X,I2,5X,I2)
 202  FORMAT(5X,I2,12X,I2,11X,I2)
 203  FORMAT(19X,I2,8X,F8.5,1X,F8.5,4X,F8.5,1X,F8.5)
!
!  Reading: EELS/(e,2e) integrals
!
 250  FORMAT(5X,4I5,2E15.7)
 260  FORMAT(5X,6I5,2E15.7)
!
!  Write formats
!
 301  FORMAT(///,3X,'<<<<<<<<<<  THE RADIAL FILE FOR THE AUGER ',   &
                 'ELECTRON IS NOT CONSISTENT   >>>>>>>>>>',/,       &
                 3X,'<<<<<<<<<<  ',17X,'WITH THE INPUT DATA FILE  ',&
                 16X,'>>>>>>>>>>',//)
 311  FORMAT(///,'<<<<<<<<<<  LI_M SHOULD BE AT LEAST ',I3,'  IN ', &
             'THE DIMENSIONNING FILE  >>>>>>>>>>',//)
!
 400  FORMAT(//,5X,'ELECTRIC DIPOLE EXCITATION    : ')
 401  FORMAT(//,5X,'ELECTRIC QUADRUPOLE EXCITATION: ')
 402  FORMAT(//,5X,'ELECTRIC OCTUPOLE EXCITATION  : ')
 403  FORMAT(//,5X,'MAGNETIC DIPOLE EXCITATION    : ')
 404  FORMAT(//,5X,'MAGNETIC QUADRUPOLE EXCITATION: ')
 405  FORMAT(//,5X,'SINGLE CHANNEL EXCITATION     : ')
!
 500  FORMAT(/,18X,'INITIAL STATE L = ',I1,5X,'FINAL STATES L = ',  &
             I1,',',I1,/)
 501  FORMAT(//,21X,'INITIAL STATE L = ',I1,5X,'FINAL STATE L = ',I1)
 502  FORMAT(15X,'(SPIN-ORBIT COMPONENT OF THE INITIAL CORE STATE : ',&
             A3,')',//)
 503  FORMAT(6X,'RADIAL MATRIX ELEMENTS FOR THE ABSORBER OF TYPE ', &
             I2,' : (',F8.5,',',F8.5,')',5X,I2,' ---> ',I2,         &
             /,59X,'(',F8.5,',',F8.5,')',5X,I2,' ---> ',I2)
 504  FORMAT(6X,'RADIAL MATRIX ELEMENTS FOR THE ABSORBER OF TYPE ', &
             I2,' : (',F8.5,',',F8.5,')',5X,I2,' ---> ',I2,         &
             /,59X,'(',F8.5,',',F8.5,')',5X,I2,' ---> ',I2,         &
             /,59X,'(',F8.5,',',F8.5,')',5X,I2,' ---> ',I2)
 505  FORMAT(6X,'RADIAL MATRIX ELEMENTS FOR THE ABSORBER OF TYPE ', &
             I2,' : (',F8.5,',',F8.5,')',5X,I2,' ---> ',I2,         &
             /,59X,'(',F8.5,',',F8.5,')',5X,I2,' ---> ',I2,         &
             /,59X,'(',F8.5,',',F8.5,')',5X,I2,' ---> ',I2,         &
             /,59X,'(',F8.5,',',F8.5,')',5X,I2,' ---> ',I2)
 506  FORMAT(6X,'RADIAL MATRIX ELEMENTS FOR THE ABSORBER OF TYPE ', &
             I2,' : (',F8.5,',',F8.5,')',5X,I2,' ---> ',I2)
 508  FORMAT(/,18X,'INITIAL STATE L = ',I1,5X,'FINAL STATES L = ',  &
             I1,',',I1,',',I1,/)
 509  FORMAT(/,18X,'INITIAL STATE L = ',I1,5X,'FINAL STATES L = ',  &
             I1,',',I1,',',I1,',',I1,/)
!
 600  FORMAT(6X,'RADIAL MATRIX ELEMENTS FOR THE ABSORBER OF TYPE ',  &
             I2,' : ',/,8X,'(LE : ALLOWED VALUES FOR ESCAPING AUGER',&
            ' ELECTRON)',/,                                          &
             8X,'(L  : INTERNAL VALUE THAT WILL BE SUMMED ON)',//)
 601  FORMAT(10X,'LE = ',I2,11X,'DIRECT INTEGRAL',8X,               &
             'EXCHANGE INTEGRAL')
 602  FORMAT(15X,'L = ',I2,5X,'(',F8.5,',',F8.5,')',5X,             &
             '(',F8.5,',',F8.5,')')
 603  FORMAT(18X,'MAXIMAL L FOR THE INCOMING ELECTRON  : ',I2)
 604  FORMAT(18X,'MAXIMAL L FOR THE SCATTERED ELECTRON : ',I2)
 605  FORMAT(18X,'MAXIMAL L FOR THE EXCITED ELECTRON   : ',I2)
 606  FORMAT(18X,'MAXIMAL L FOR THE COULOMB FIELD      : ',I2)
!
 700  FORMAT(6X,'NO INTERACTION CASE')
!
 888  RETURN                                                        !
!
      END SUBROUTINE READ_RADIAL
!
!=======================================================================
!
      SUBROUTINE INIT_EELS_ARRAYS(RHOL_00_RD,RHOL_00_RE,RHOL_0J_RD, &
                                  RHOL_0J_RE,RHOL_ID,RHOL_IE)
!
!  This subroutine initializes the radial integral arrays read in. This is
!    necessary as only the meaningful values are read (the values lower
!    than 1.e-9 in modulus have not been printed in the radial file
!
!  Output variables :
!
!                       RHOL_00_RD :  one-site regular direct integrals
!                       RHOL_00_RE :  one-site regular exchange integrals
!                       RHOL_0J_RD :  two-site regular direct integrals
!                       RHOL_0J_RE :  two-site regular exchange integrals
!                       RHOL_ID    :  irregular direct integrals
!                       RHOL_IE    :  irregular direct integrals
!
!
!
!   Author :  D. Sébilleau
!
!                                         Last modified : 19 May 201
!
!
      USE COMPLEX_NUMBERS,            ONLY : ZEROC
!
      IMPLICIT NONE
!
      INTEGER                    ::  JE,JAT
      INTEGER                    ::  L_EX,L_IN
      INTEGER                    ::  L_O1,L_C1,L_C2
!
      COMPLEX (WP), INTENT(OUT)  ::  RHOL_00_RD(NE_M,0:NL_M,0:NL_M,0:NL_M,0:2*NL_M)
      COMPLEX (WP), INTENT(OUT)  ::  RHOL_00_RE(NE_M,0:NL_M,0:NL_M,0:NL_M,0:2*NL_M)
      COMPLEX (WP), INTENT(OUT)  ::  RHOL_0J_RD(NE_M,NATCLU_M,0:NL_M,0:NL_M,0:NL_M,0:2*NL_M,0:2*NL_M)
      COMPLEX (WP), INTENT(OUT)  ::  RHOL_0J_RE(NE_M,NATCLU_M,0:NL_M,0:NL_M,0:NL_M,0:2*NL_M,0:2*NL_M)
      COMPLEX (WP), INTENT(OUT)  ::  RHOL_ID(NE_M,0:NL_M,0:NL_M,0:NL_M,0:2*NL_M)
      COMPLEX (WP), INTENT(OUT)  ::  RHOL_IE(NE_M,0:NL_M,0:NL_M,0:NL_M,0:2*NL_M)
!
!
!  (1) One-site regular integrals
!
      DO JE = 1, NE_M                                               !
        DO L_EX = 0, NL_M                                           !
          DO L_IN = 0, NL_M                                         !
            DO L_O1 = 0, NL_M                                       !
              DO L_C1 = 0, 2*NL_M                                   !
                RHOL_00_RD(JE,L_EX,L_IN,L_O1,L_C1) = ZEROC          !
                RHOL_00_RE(JE,L_EX,L_IN,L_O1,L_C1) = ZEROC          !
              END DO                                                !
            END DO                                                  !
          END DO                                                    !
        END DO                                                      !
      END DO                                                        !
!
!  (2) Two-site regular integrals
!
      DO JE = 1, NE_M                                               !
        DO JAT = 1, NATCLU_M                                        !
          DO L_EX = 0, NL_M                                         !
            DO L_IN = 0, NL_M                                       !
              DO L_O1 = 0, NL_M                                     !
                DO L_C1 = 0, 2*NL_M                                 !
                  DO L_C2 = 0, 2*NL_M                               !
                    RHOL_0J_RD(JE,JAT,L_EX,L_IN,L_O1,L_C1,L_C2) = ZEROC
                    RHOL_0J_RE(JE,JAT,L_EX,L_IN,L_O1,L_C1,L_C2) = ZEROC
                  END DO                                            !
                END DO                                              !
              END DO                                                !
            END DO                                                  !
          END DO                                                    !
        END DO                                                      !
      END DO                                                        !
!
!  (3) Irregular integrals
!
      DO JE = 1, NE_M                                               !
        DO L_EX = 0, NL_M                                           !
          DO L_IN = 0, NL_M                                         !
            DO L_O1 = 0, NL_M                                       !
              DO L_C1 = 0, 2*NL_M                                   !
                RHOL_ID(JE,L_EX,L_IN,L_O1,L_C1) = ZEROC             !
                RHOL_IE(JE,L_EX,L_IN,L_O1,L_C1) = ZEROC             !
              END DO                                                !
            END DO                                                  !
          END DO                                                    !
        END DO                                                      !
      END DO                                                        !
!
      END SUBROUTINE INIT_EELS_ARRAYS
!
!=======================================================================
!
      SUBROUTINE FIND_EELS_BLOCKS(IUN,IUO1,NE,NLINE_1,NLINE_2,      &
                                  NLINE_3,NLINE_4,NLINE_5,NLINE_6)
!
!  This subroutine computes the length of the different blocks of radial
!      integrals to read from the EELS radial file. These numbers
!      cannot be known in advance as phagen_scf.f only prints the
!      radial integrals larger in modulus than 1.E-9
!
!
!  Input variables :
!
!                       IUN       :  Fortran unit for the EELS radial integrals
!                       IUO1      :  Fortran unit for the check file
!                       NE        :  number of energy points
!
!
!  Output variables :
!
!                       NLINE_1   :  length of the single site regular direct block
!                       NLINE_2   :  length of the two-site regular direct block
!                       NLINE_3   :  length of the single site regular exchange block
!                       NLINE_4   :  length of the two-site regular exchange block
!                       NLINE_5   :  length of the irregular direct block
!                       NLINE_6   :  length of the irregular exchange block
!
!
!
!   Author :  D. Sébilleau
!
!                                         Last modified : 19 May 201
!
!
      IMPLICIT NONE
!
      CHARACTER (LEN = 38)  ::  RADTYP(6),ENERGY,DUMMY
!
      INTEGER, INTENT(IN)   ::  IUN,IUO1,NE
      INTEGER, INTENT(OUT)  ::  NLINE_1(NE_M),NLINE_2(NE_M)
      INTEGER, INTENT(OUT)  ::  NLINE_3(NE_M),NLINE_4(NE_M)
      INTEGER, INTENT(OUT)  ::  NLINE_5(NE_M),NLINE_6(NE_M)
!
      INTEGER               ::  JBLOCK(NE_M)
      INTEGER               ::  JE,JL,NL,N_LINES
      INTEGER               ::  N_E,JLINE,NLIN
      INTEGER               ::  N_ABS
!
      INTEGER, PARAMETER    ::  NLINES = 900000
!
      DATA ENERGY /'           ---> energy point number   '/
      DATA RADTYP /'          single site regular direct t',  &
                   '          two-site regular direct term',  &
                   '          single site regular exchange',  &
                   '          two-site regular exchange te',  &
                   '          irregular direct terms:     ',  &
                   '          irregular exchange terms    '/
!
!  Initialization
!
      DO JE = 1, NE                                                 !
        JBLOCK(JE) = 0                                              !
      END DO                                                        !
!
!  Finding the number of lines of the radial file
!
      NL      = NLINES                                              !
   20 N_LINES = 0                                                   !
      DO JL = 1, NL                                                 !
        READ(IUN,100,END=10) DUMMY                                  !
        N_LINES = N_LINES + 1                                       !
      END DO                                                        !
      IF(N_LINES == NLINES) THEN                                    !
         NL = NL + NLINES                                           !
      END IF                                                        !
      GO TO 20                                                      !
!
   10 WRITE(IUO1,200) N_LINES                                       !
!
      REWIND IUN                                                    !
!
!  Checking the number of energy points
!
      N_E = 0                                                       !
      DO JL = 1, N_LINES                                            !
        READ(IUN,110) DUMMY                                         !
        IF(DUMMY == ENERGY) THEN                                    !
           N_E = N_E + 1                                            !
           JBLOCK(N_E) = JL                                         ! start of energy block N_E
        END IF                                                      !
      END DO                                                        !
      IF(N_E == NE) THEN                                            !
        IF(N_E == 1) THEN                                           !
          WRITE(IUO1,210) N_E                                       !
        ELSE                                                        !
          WRITE(IUO1,211) N_E                                       !
        END IF                                                      !
      ELSE                                                          !
        WRITE(IUO1,220) N_E                                         !
      END IF                                                        !
!
      REWIND IUN                                                    !
!
!  Finding the number of lines of each set of terms
!
      DO JE = 1, N_E                                                !
!
        DO JLINE = 1, JBLOCK(JE)                                    ! skipping all lines until
          READ(IUN,100) DUMMY                                       ! the start of the energy
        END DO                                                      ! block JE
!
!  Start of block JE
!
        READ(IUN,100) DUMMY                                         !
!
        IF(DUMMY == RADTYP(1)) THEN                                 !
!
!..........  single site regular direct terms:  ..........
!
          READ(IUN,100) DUMMY                                       !
          NLIN = 0                                                  !
          DO JL = 1, N_LINES                                        !
            READ(IUN,120,ERR=30) N_ABS                              ! reads integer until it finds -----
            NLIN = NLIN + 1                                         !
          END DO                                                    !
   30     NLINE_1(JE) = NLIN                                        !
        END IF                                                      !
!
        READ(IUN,100) DUMMY                                         !
!
        IF(DUMMY == RADTYP(2)) THEN                                 !
!
!..........  two-site regular direct terms:  ..........
!
          READ(IUN,100) DUMMY                                       !
          NLIN = 0                                                  !
          DO JL = 1, N_LINES                                        !
            READ(IUN,120,ERR=40) N_ABS                              ! reads integer until it finds -----
            NLIN = NLIN + 1                                         !
          END DO                                                    !
   40     NLINE_2(JE) = NLIN                                        !
        END IF                                                      !
!
        READ(IUN,100) DUMMY                                         !
!
        IF(DUMMY == RADTYP(3)) THEN                                 !
!
!..........  single site regular exchange terms:  ..........
!
          READ(IUN,100) DUMMY                                       !
          NLIN = 0                                                  !
          DO JL = 1,N_LINES                                         !
            READ(IUN,120,ERR=50) N_ABS                              ! reads integer until it finds -----
            NLIN = NLIN + 1                                         !
          END DO                                                    !
   50     NLINE_3(JE) = NLIN                                        !
        END IF                                                      !
!
        READ(IUN,100) DUMMY                                         !
!
        IF(DUMMY == RADTYP(4)) THEN                                 !
!
!..........  two-site regular exchange terms:  ..........
!
          READ(IUN,100) DUMMY                                       !
          NLIN = 0                                                  !
          DO JL = 1, N_LINES                                        !
            READ(IUN,120,ERR=60) N_ABS                              ! reads integer until it finds -----
            NLIN = NLIN + 1                                         !
          END DO                                                    !
   60     NLINE_4(JE) = NLIN                                        !
        END IF                                                      !
!
        READ(IUN,100) DUMMY                                         !
!
        IF(DUMMY == RADTYP(5)) THEN                                 !
!
!..........  irregular direct terms:  ..........
!
          READ(IUN,100) DUMMY                                       !
          NLIN = 0                                                  !
          DO JL = 1, N_LINES                                        !
            READ(IUN,120,ERR=70) N_ABS                              ! reads integer until it finds -----
            NLIN = NLIN + 1                                         !
          END DO                                                    !
   70     NLINE_5(JE) = NLIN                                        !
        END IF                                                      !
!
        READ(IUN,100) DUMMY                                         !
!
        IF(DUMMY == RADTYP(6)) THEN                                 !
!
!..........  irregular exchange terms:  ..........
!
          READ(IUN,100) DUMMY                                       !
          NLIN = 0                                                  !
          DO JL = 1, N_LINES                                        !
            READ(IUN,120,ERR=80) N_ABS                              ! reads integer until it finds -----
            NLIN = NLIN + 1                                         !
          END DO                                                    !
   80     NLINE_6(JE) = NLIN                                        !
        END IF                                                      !
!
!  End of block JE
!
        REWIND IUN                                                  !
!
      END DO                                                        !
!
      REWIND IUN                                                    !
!
!  Writing the length of the blocks in the check file
!
      DO JE = 1, N_E                                                !
        WRITE(IUO1,224)                                             !
        WRITE(IUO1,225) JE                                          !
        WRITE(IUO1,230) NLINE_1(JE)                                 !
        WRITE(IUO1,240) NLINE_2(JE)                                 !
        WRITE(IUO1,250) NLINE_3(JE)                                 !
        WRITE(IUO1,260) NLINE_4(JE)                                 !
        WRITE(IUO1,270) NLINE_5(JE)                                 !
        WRITE(IUO1,280) NLINE_6(JE)                                 !
        WRITE(IUO1,224)                                             !
        WRITE(IUO1,290)                                             !
      END DO
!
!  Read formats:
!
  100 FORMAT(A38)
  110 FORMAT(39X,A38)
  120 FORMAT(4X,I1)
!
!  Write formats:
!
  200 FORMAT(3X,'---> THE EELS/E2E RADIAL MATRIX FILE CONTAINS ',     &
             I10,' LINES')
  210 FORMAT(8X,'AND ',I5,' ENERGY POINT',/)
  211 FORMAT(8X,'AND ',I5,' ENERGY POINTS',/)
  220 FORMAT(///,10X,'<<<<<<<<<<  ERROR IN RADIAL FILE: ',I5,         &
             ' ENERGY POINTS  >>>>>>>>>>',/,                          &
                 10X,'<<<<<<<<<<     NOT CONSISTENT WITH INPUT DATA ',&
              'FILE     >>>>>>>>>>')
  224 FORMAT(10X,'!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!',          &
                '!!!!!!!!!!!!!!!!!!!!!')
  225 FORMAT(10X,'! ENERGY BLOCK ',I5,' CONTAINS:',30X,'!')
  230 FORMAT(10X,'! ',I10,' LINES OF ONE-SITE REGULAR DIRECT TERMS',  &
              9X,'!')
  240 FORMAT(10X,'! ',I10,' LINES OF TWO-SITE REGULAR DIRECT TERMS',  &
              9X,'!')
  250 FORMAT(10X,'! ',I10,' LINES OF ONE-SITE REGULAR EXCHANGE TERMS',&
              7X,'!')
  260 FORMAT(10X,'! ',I10,' LINES OF TWO-SITE REGULAR EXCHANGE TERMS',&
              7X,'!')
  270 FORMAT(10X,'! ',I10,' LINES OF IRREGULAR DIRECT TERMS',16X,'!')
  280 FORMAT(10X,'! ',I10,' LINES OF IRREGULAR EXCHANGE TERMS',14X,'!')
  290 FORMAT('         ')
!
      END SUBROUTINE FIND_EELS_BLOCKS
!
!=======================================================================
!
      SUBROUTINE READ_CORE_WF(IUI3,IUO1,INFILE3)
!
!  This subroutine reads the core state wave function on the log-linear mesh
!    and stores it in the common block /CORE_WF/
!
!
!  Input variables :
!
!                       IUI3      :  Fortran unit for the core state wave function file
!                       INFILE3   :  name of the core state wave function file (24 char. max)
!                       IUO1      :  Fortran unit for the check file *.lis
!
!
!
!   Author :  D. Sébilleau
!
!                                     Last modified : 12 May 2021
!
!
      USE WAVE_FUNCTION
!
      IMPLICIT NONE
!
      CHARACTER (LEN = 34)  ::  HEADER
      CHARACTER (LEN = 24)  ::  INFILE3
!
      INTEGER, INTENT(IN)   ::  IUI3,IUO1
!
      INTEGER               ::  I
!
      OPEN(UNIT=IUI3, FILE=INFILE3, STATUS='old')
!
      READ(IUI3,10) HEADER                                          !
!
!  Checking if the file is on the lin-log mesh
!
      IF(HEADER(14:20) /= 'lin-log') THEN                           !
        WRITE(IUO1,110)                                             !
        STOP                                                        !
      END IF                                                        !
!
      DO I = 1, N_MESH_M                                            !
        READ(IUI3,20,END=200) R(I),COREWF(I)                        !
      END DO                                                        !
!
 200  CLOSE(IUI3)                                                   !
!
!  Formats:
!
  10  FORMAT(A34)
  20  FORMAT(2E13.6)
!
 110  FORMAT(///,10X,'<<<<<<<<<<   WRONG CORE STATE FILE:    ',     &
                '>>>>>>>>>>',/,10X,'<<<<<<<<<<  SHOULD BE ON ',     &
                'LIN-LOG MESH  >>>>>>>>>>')
!
      END SUBROUTINE READ_CORE_WF
!
!=======================================================================
!
      SUBROUTINE READ_CLUSTER(IUO1,IUIN,INFILE,IPRINT,IPHA,ZEM)
!
!  This routine writes the information on the spectroscopy selected into the check file
!     at the end of the calculation
!
!  Input variables :
!
!                       IUO1      :  Fortran unit for the check file *.lis
!                       IUIN      :  Fortran unit for the cluster file
!                       INFILE    :  cluster filename
!                       IPRINT    :  switch to control the printing
!
!
!  Output variables :
!
!                       IPHA      :  switch for phagen_scf.f
!                       ZEM       :  z position of absorber
!
!
!   Author :  D. Sébilleau
!
!                                     Last modified : 28 May 2021
!
!
      USE REAL_NUMBERS,     ONLY : ZERO,ONE,LARGE
      USE CONSTANTS_P1,     ONLY : BOHR
!
      USE SORT1,            ONLY : SORT_DEC
!
      USE ABSORBER
      USE ATOMIC_INDEX
      USE ATOMS
      USE CLUSTER
      USE CLUSTER_COORD
      USE CLUSTER_LIMITS
!
      IMPLICIT NONE
!
      CHARACTER (LEN = 30)   ::  TUNIT
      CHARACTER (LEN = 24)   ::  INFILE
      CHARACTER (LEN =  2)   ::  R
!
      INTEGER, INTENT(IN)    ::  IUO1,IUIN,IPRINT
      INTEGER, INTENT(OUT)   ::  IPHA
!
      INTEGER                ::  JAT,JA1,JA2,J,JEMED
      INTEGER                ::  K,L,JPLAN
      INTEGER                ::  JA,JC,JTYP,JATM,JLINE
      INTEGER                ::  NB_AT,NBZ,NAT_ST
      INTEGER                ::  NN
!
      INTEGER, PARAMETER     ::  NLINE = 10000
!
      REAL (WP), INTENT(OUT) ::  ZEM
!
      REAL (WP)              ::  COORD(3,NATCLU_M)
      REAL (WP)              ::  DIST12(NATCLU_M,NATCLU_M)
      REAL (WP)              ::  SMALL,SSMALL
      REAL (WP)              ::  CUNIT,D_UP,D_DO
      REAL (WP)              ::  X,Y,Z,VALZ_MIN
!
      REAL (WP)              ::  SQRT,MIN,MAX
!
      DATA SMALL,SSMALL / 0.001E0_WP, 0.0001E0_WP /
!
!  Cluster originating from CLUSTER_NEW.F : IPHA=0                                        ! deprecated
!  Cluster originating from PHAGEN_NEW.F  : IPHA=1 (atomic units), IPHA=2 (angstroems)
!  Other cluster                          : the first line must be text; then
!                                            free format : Atomic number,X,Y,Z,number
!                                            of the corresponding prototypical atom ;
!                                            All atoms corresponding to the same
!                                            prototypical atom must follow each other.
!                                            Moreover, the blocks of equivalent atoms
!                                            must be ordered by increasing number of
!                                            prototypical atom.
!
      VALZ_MIN =   1000.0E0_WP                                      !
      VALZ_MAX = - 1000.0E0_WP                                      !
!
      OPEN(UNIT=IUIN, FILE=INFILE, STATUS='OLD')                    !
!
      READ(IUIN,10,ERR=800) IPHA                                    !
      GO TO 801                                                     !
!
  800 IPHA = 3                                                      !
      IF(UNIT == 'ANG') THEN                                        !
        CUNIT = ONE / A                                             !
        TUNIT = 'ANGSTROEMS'                                        !
      ELSE IF(UNIT == 'LPU') THEN                                   !
        CUNIT = ONE                                                 !
        TUNIT = 'UNITS OF THE LATTICE PARAMETER'                    !
      ELSE IF(UNIT == 'ATU') THEN                                   !
        CUNIT = BOHR / A                                            !
        TUNIT = 'ATOMIC UNITS'                                      !
      ELSE                                                          !
        GO TO 802                                                   !
      END IF                                                        !
!
  801 NATCLU = 0                                                    !
!
      DO JAT = 1, NAT                                               !
        NATYP(JAT) = 0                                              !
      END DO                                                        !
      IF(IPHA == 0) THEN                                            !
        CUNIT = ONE                                                 !
        TUNIT= 'UNITS OF THE LATTICE PARAMETER'                     !
      ELSE IF(IPHA == 1) THEN                                       !
        CUNIT = BOHR / A                                            !
        TUNIT = 'ATOMIC UNITS'                                      !
      ELSE IF(IPHA == 2) THEN                                       !
        CUNIT = ONE / A                                             !
        TUNIT = 'ANGSTROEMS'                                        !
      END IF                                                        !
!
      IF(IPRINT == 2) THEN                                          !
        IF(I_AT /= 1) THEN                                          !
          WRITE(IUO1,110) IUIN,TUNIT                                !
          IF(IPHA == 3) WRITE(IUO1,111)                             !
        END IF                                                      !
      END IF                                                        !
!
      JATM = 0                                                      !
      DO JLINE = 1, NLINE                                           !
        IF(IPHA == 0) THEN                                          !
          READ(IUIN,11,END=803) R,NN,X,Y,Z,JAT                      !
        ELSE IF(IPHA == 1) THEN                                     !
          READ(IUIN,12,END=803) R,NN,X,Y,Z,JAT                      !
        ELSE IF(IPHA == 2) THEN                                     !
          READ(IUIN,12,END=803) R,NN,X,Y,Z,JAT                      !
        ELSE IF(IPHA == 3) THEN                                     !
          READ(IUIN,*,END=803) NN,X,Y,Z,JAT                         !
        END IF                                                      !
!
        JATM   = MAX(JAT,JATM)                                      !
        NATCLU = NATCLU + 1                                         !
!
        IF(IPHA /= 3) THEN                                          !
          CHEM(JAT) = R                                             !
        ELSE                                                        !
          CHEM(JAT)=  'XX'                                          !
        END IF                                                      !
!
        NZAT(JAT)  = NN                                             !
        NATYP(JAT) = NATYP(JAT) + 1                                 !
!
        COORD(1,NATCLU) = X * CUNIT                                 !
        COORD(2,NATCLU) = Y * CUNIT                                 !
        COORD(3,NATCLU) = Z * CUNIT                                 !
!
        VALZ(NATCLU) = Z * CUNIT                                    !
!
        IF((IPRINT >= 2) .AND. (I_AT == 0)) THEN                    !
          WRITE(IUO1,112) NATCLU,COORD(1,NATCLU),COORD(2,NATCLU), & !
                          COORD(3,NATCLU),JAT,NATYP(JAT),CHEM(JAT)  !
        END IF                                                      !
      END DO                                                        !
!
!  Coordinates of the absorber
!
 803  EMIT(1) = COORD(1,1)                                          !
      EMIT(1) = COORD(2,1)                                          !
      EMIT(1) = COORD(2,1)                                          !
      NTYPEM  = 1                                                   !
      NEMET   = 1                                                   !
!
      NBZ = NATCLU                                                  !
      IF(JATM /= NAT) GO TO 804                                     !
      CLOSE(IUIN)                                                   !
!
      IF(NATCLU > NATCLU_M) GO TO 805                               !
      DO JA1=  1, NATCLU                                            !
        DO JA2 = 1,NATCLU                                           !
          DIST12(JA1,JA2) = SQRT( (COORD(1,JA1) - COORD(1,JA2))**2& !
                                + (COORD(2,JA1) - COORD(2,JA2))**2& !
                                + (COORD(3,JA1) - COORD(3,JA2))**2& !
                                )                                   !
          IF((JA2 > JA1) .AND. (DIST12(JA1,JA2) < 0.001)) GO TO 806 !
        END DO                                                      !
      END DO                                                        !
!
      D_UP = VALZ_MAX - VALZ(1)                                     !
      D_DO = VALZ(1) - VALZ_MIN                                     !
!
      IF((D_DO <= D_UP) .AND. (I_GR == 2)) THEN                     !
        I_INV = 1                                                   !
      ELSE                                                          !
        I_INV = 0                                                   !
      END IF                                                        !
!
!  Storage of the extremal values of x and y for each plane. They define
!    the exterior of the cluster when a new cluster has to be build to
!    support a point-group
!
      IF(I_GR >= 1) THEN                                            !
        CALL SORT_DEC(NBZ,VALZ,NPLAN,VAL)                           !
        WRITE(IUO1,113) NPLAN                                       !
        DO K = 1, NPLAN                                             !
          WRITE(IUO1,114) K,VAL(K)                                  !
          X_MAX(K) = ZERO                                           !
          X_MIN(K) = ZERO                                           !
          Y_MAX(K) = ZERO                                           !
          Y_MIN(K) = ZERO                                           !
        END DO                                                      !
        DO JAT = 1, NATCLU                                          !
          X = COORD(1,JAT)                                          !
          Y = COORD(2,JAT)                                          !
          Z = COORD(3,JAT)                                          !
          DO JPLAN = 1, NPLAN                                       !
            IF(ABS(Z-VAL(JPLAN)) < SSMALL) THEN                     !
              X_MAX(JPLAN) = MAX(X,X_MAX(JPLAN))                    !
              X_MIN(JPLAN) = MIN(X,X_MIN(JPLAN))                    !
              Y_MAX(JPLAN) = MAX(Y,Y_MAX(JPLAN))                    !
              Y_MIN(JPLAN) = MIN(Y,Y_MIN(JPLAN))                    !
            END IF                                                  !
          END DO                                                    !
        END DO                                                      !
      END IF                                                        !
!
!  Instead of the symmetrization of the cluster (this version only)
!
      N_PROT = NAT                                                  !
      NAT_ST = 0                                                    !
      DO JTYP = 1, JATM                                             !
       NB_AT = NATYP(JTYP)                                          !
       IF(NB_AT > NAT_EQ_M) GO TO 807                               !
       DO JA = 1, NB_AT                                             !
         NAT_ST         = NAT_ST + 1                                !
         NCORR(JA,JTYP) = NAT_ST                                    !
       END DO                                                       !
      END DO                                                        !
      DO JC = 1, 3                                                  !
        DO JA = 1, NATCLU                                           !
          SYM_AT(JC,JA) = COORD(JC,JA)                              !
        END DO                                                      !
      END DO                                                        !
!
!..........  Writing of the contents of the cluster,  ..........
!..........  of the position of the different planes  ..........
!..........   and of their respective absorbers in    ..........
!..........          the control file IUO1            ..........
!
      IF(I_AT == 0) WRITE(IUO1,115)                                 !
      ZEM = COORD(3,1)                                              !
!
      GO TO 888                                                     !
!
!  Stops for dimension problems
!
 805  WRITE(IUO1,200) IUIN                                          !
      STOP                                                          !
 804  WRITE(IUO1,201)                                               !
      STOP                                                          !
 807  WRITE(IUO1,202) NB_AT                                         !
      STOP                                                          !
 802  WRITE(IUO1,203)                                               !
      STOP                                                          !
 806  WRITE(IUO1,204) JA1,JA2                                       !
!
!  Formats:
!
  10  FORMAT(30X,I1)
  11  FORMAT(11X,A2,5X,I2,3F10.4,12X,I4)
  12  FORMAT(11X,A2,5X,I2,3F10.4,I5)
!
 110  FORMAT(/////,18X,'CONTENTS OF THE CLUSTER READ FROM UNIT ',      &
             I2,' : ',/,20X,'READ IN ',A30,//,15X,'No',13X,'(X,Y,Z)',  &
             10X,'CLASS',1X,'ATOM',/)
 111  FORMAT(//,14X,' No ',10X,'COORDINATES',9X,'TYPE',2X,             &
             'SNo',2X,'SYM',/)
 112  FORMAT(13X,I4,3X,'(',F7.3,',',F7.3,',',F7.3,')',2X,I4,2X,I4,     &
              3X,A2)
 113  FORMAT(///,22X,'THE CLUSTER IS COMPOSED OF ',I2,' PLANES :')
 114  FORMAT(/,20X,'THE Z POSITION OF PLANE ',I3,' IS : ',F6.3)
 115  FORMAT(///,23X,'THE ABSORBING ATOMS ARE OF TYPE 1',/)
!
 200  FORMAT(///,'<<<<<<<<<<  NATCLU_M IN THE .inc FILE IS NOT ',      &
             'CONSISTENT WITH THE NUMBER OF ATOMS READ FROM UNIT ',I2, &
             '  >>>>>>>>>>')
 201  FORMAT(///,'<<<<<<<<<<  INCOMPATIBILITY BETWEEN THE VALUES OF ', &
             'NAT IN THE DATA AND CLUSTER FILES  >>>>>>>>>>')
 202  FORMAT(///,'<<<<<<<<<<  NAT_EQ_M SHOULD BE AT LEAST ',I3,'  IN ',&
             'THE DIMENSIONNING FILE  >>>>>>>>>>',//)
 203  FORMAT(/////,'<<<<<<<<<<  WRONG NAME FOR THE COORDINATES ''',    &
             'UNITS  >>>>>>>>>>')
 204  FORMAT(///,10X,'<<<<<<<<<<  ERROR IN THE COORDINATES OF THE',    &
             '  ATOMS  >>>>>>>>>>',/,10X,'<<<<<<<<<<     ATOMS ',I4,   &
             ' AND ',I4,' ARE IDENTICAL    >>>>>>>>>>')
!
 888  RETURN
!
      END SUBROUTINE READ_CLUSTER
!
END MODULE READ_EXT_FILES
