#! /bin/bash -f
clear
echo "                                                 "
echo "                                                 "
echo "*************************************************"
echo "*                                               *"
echo "*                  PROCESSING                   *"
echo "*            A SCATTERING FACTOR FILE           *"
echo "*                                               *"
echo "*************************************************"
echo "                                                 "
echo "                                                 "
#
#  If you want the CPU time of your calculation to be 
#    printed into a separate file, uncomment and 
#    customize the commented lines to your needs
#
#
#echo "  " >> cpu.res 2>&1
#echo "=============================" >> cpu.res 2>&1
#echo "  " >> cpu.res 2>&1
#date >> cpu.res 2>&1
#echo "             +++             " >> cpu.res 2>&1
#echo " Input data file : spec.dat :" >> cpu.res 2>&1
#echo "             +++             " >> cpu.res 2>&1
#echo " CPU time :" >> cpu.res 2>&1
#echo "  " >> cpu.res 2>&1
#
#(time  -p  ./spec  <<Fin)  >> cpu.res 2>&1
#
time -p treatment/fdplot <<Fin >& error.dat
input_file.dat                          #  Format(A18) 
output_file.dat                         #  Format(A18)
1                                       #  Modulus of SF
2                                       #  as a function of theta
3                                       #  in polar coordinates
4                                       #  Number of atom
N                                       #  No other plot
N                                       #  No other file
Fin
#
#  Checking for a blend of dialog
#
DIAL=`which dialog | cut -d: -f2 | grep -c 'dialog'`
XDIA=`which Xdialog | cut -d: -f2 | grep -c 'Xdialog'`
KDIA=`which kdialog | cut -d: -f2 | grep -c 'kdialog'`
ZENI=`which zenity | cut -d: -f2 | grep -c 'zenity'`
#
if [ "$ZENI" -ne "0" ]; then
  DIALOG=zenity
else
  if [ "$XDIA" -ne "0" ]; then
    DIALOG=Xdialog
  else
    if [ "$KDIA" -ne "0" ]; then
      DIALOG=kdialog
    else
      if [ "$DIAL" -ne "0" ]; then
        DIALOG=dialog
      else
        DIALOG=none
      fi
    fi
  fi
fi
#
ERR=`cat error.dat`
NLINE=`cat error.dat | wc -l`
#
if [ $NLINE != 0 ]; then
  if [ "$DIALOG" = "Xdialog" ]; then
    Xdialog --title "MsSpec-0.1 runtime error" \
            --backtitle "The code has stopped with the message : \n \n  \n " \
            --msgbox " 
    $ERR 
    " 0 0
  elif [ "$DIALOG" = "zenity" ]; then
    zenity --width 400 --height 180 \
           --title "MsSpec-0.1 runtime error" \
           --info --text "The code has stopped with the message : \n \n  \n $ERR" \
           --timeout 5 
  fi
fi
#
rm -f error.dat
#
exit
